perSystem: Add custom error messages for learning about top level module args
Example:

```
error: `self` (without `'`) is not a `perSystem` module argument, but a
       module argument  of the top level config.

       The following is an example usage of `self`. Note that its binding
       is in the `top` parameter list, which is declared by the top level module
       rather than the `perSystem` module.

         top@{ config, lib, self, ... }: {
           perSystem = { config, self', ... }: {
             # in scope here:
             #  - self
             #  - self'
             #  - config (of perSystem)
             #  - top.config (note the `top@` pattern)
           };
         }
```